"""Generate the parameters reference (Markdown) from the schema.

The reference is committed as ``docs/parameters.md`` and a test checks it is
up to date, so it cannot drift from :mod:`evacusim.config.schema`.
Regenerate it after changing the schema::

    python -m evacusim.config.reference > docs/parameters.md
"""

from __future__ import annotations

import inspect
import re
import types
import typing
from typing import Any, Literal

from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from evacusim.config import schema

HEADER = """\
# Parameters reference

<!-- Generated by `python -m evacusim.config.reference`; do not edit by hand. -->

Every key a run configuration may contain. Keys not listed here are rejected.
Values are not coerced between types, except that an integer is accepted
where a number is expected.

"""


def _type_name(annotation: Any) -> str:
    """A short, readable name for a field's type."""
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin is typing.Annotated:
        return _type_name(args[0])
    if origin in (typing.Union, types.UnionType):
        return " \\| ".join(_type_name(a) for a in args)
    if origin is Literal:
        return " \\| ".join(f"`{a!r}`".replace("'", '"') for a in args)
    if origin is list:
        return f"list[{_type_name(args[0])}]"
    if origin is dict:
        return f"map[{_type_name(args[0])} → {_type_name(args[1])}]"
    if annotation is type(None):
        return "null"
    if inspect.isclass(annotation) and issubclass(annotation, BaseModel):
        return annotation.__name__
    return getattr(annotation, "__name__", str(annotation))


def _default(field: FieldInfo) -> str:
    if field.is_required():
        return "**required**"
    if field.default_factory is not None:
        value = field.default_factory()
        if isinstance(value, BaseModel):
            return "*(see below)*"
    else:
        value = field.default
    if value is PydanticUndefined:
        return ""
    if value is None:
        return "null"
    return f"`{value!r}`".replace("'", '"').replace("True", "true").replace("False", "false")


def _description(field: FieldInfo) -> str:
    text = field.description or ""
    constraints = [
        f"{symbol} {getattr(meta, attr)}"
        for meta in field.metadata
        for attr, symbol in (("gt", ">"), ("ge", "≥"), ("lt", "<"), ("le", "≤"))
        if getattr(meta, attr, None) is not None
    ]
    if constraints:
        text = f"{text} ({', '.join(constraints)})".strip()
    return re.sub(r"\s+", " ", text).replace("|", "\\|")


def _models_in(annotation: Any, path: str) -> list[tuple[str, type[BaseModel]]]:
    """Section models referenced by a field's type, with the path to document them at.

    Lists add ``[]`` and maps add ``.<name>`` to the path.
    """
    if inspect.isclass(annotation) and issubclass(annotation, BaseModel):
        return [(path, annotation)]
    origin, args = typing.get_origin(annotation), typing.get_args(annotation)
    if origin is list:
        return _models_in(args[0], f"{path}[]")
    if origin is dict:
        return _models_in(args[1], f"{path}.<name>")
    return [found for arg in args for found in _models_in(arg, path)]


def _first_paragraph(model: type[BaseModel]) -> str:
    """The model's own docstring (not one inherited from a base class)."""
    doc = model.__dict__.get("__doc__") or ""
    return re.sub(r"\s+", " ", inspect.cleandoc(doc).split("\n\n")[0]).strip()


def render_markdown() -> str:
    """The full reference, one table per section model."""
    out = [HEADER]
    seen: set[tuple[str, type[BaseModel]]] = set()
    queue: list[tuple[str, type[BaseModel]]] = [("(top level)", schema.RunConfig)]
    while queue:
        path, model = queue.pop(0)
        if (path, model) in seen:
            continue
        seen.add((path, model))
        out.append(f"## `{path}` — {model.__name__}\n")
        intro = _first_paragraph(model)
        if intro and model is not schema.RunConfig:
            out.append(f"{intro}\n")
        out.append("| Key | Type | Default | Meaning |\n|---|---|---|---|")
        nested = []
        for name, field in model.model_fields.items():
            out.append(
                f"| `{name}` | {_type_name(field.annotation)} | {_default(field)} "
                f"| {_description(field)} |"
            )
            field_path = name if model is schema.RunConfig else f"{path}.{name}"
            nested += _models_in(field.annotation, field_path)
        out.append("")
        queue = nested + queue
    return "\n".join(out)


if __name__ == "__main__":
    print(render_markdown(), end="")
